"""added plot column as text

Revision ID: 4340795a89ef
Revises: 686e6960cfc7
Create Date: 2020-04-27 13:21:39.695130

"""
from alembic import op
import sqlalchemy as sa
import flask_appbuilder

# revision identifiers, used by Alembic.
revision = '4340795a89ef'
down_revision = '686e6960cfc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('estimated', sa.Column('plot_png', flask_appbuilder.models.mixins.ImageColumn(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('estimated', 'plot_png')
    # ### end Alembic commands ###
