"""added year column

Revision ID: 54e1ddbe5b29
Revises: 98774552c683
Create Date: 2020-05-14 11:49:25.468905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54e1ddbe5b29'
down_revision = '98774552c683'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exposure', sa.Column('year', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exposure', 'year')
    # ### end Alembic commands ###
