"""removed plot column

Revision ID: 686e6960cfc7
Revises: c6e9db7a0813
Create Date: 2020-04-27 13:20:51.739790

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '686e6960cfc7'
down_revision = 'c6e9db7a0813'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('estimated', 'plot_png')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('estimated', sa.Column('plot_png', postgresql.BYTEA(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
