"""added molweight

Revision ID: 98774552c683
Revises: f05bc5ceed3e
Create Date: 2020-05-07 12:12:12.319983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98774552c683'
down_revision = 'f05bc5ceed3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chemical', sa.Column('molecular_weight', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chemical', 'molecular_weight')
    # ### end Alembic commands ###
