"""chemical property column changed from jsonb to float

Revision ID: c6e9db7a0813
Revises: fcf133bf0474
Create Date: 2020-04-27 12:44:53.389756

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c6e9db7a0813'
down_revision = 'fcf133bf0474'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chemical', sa.Column('estimated_henry_constant', sa.Float(), nullable=True))
    op.add_column('chemical', sa.Column('estimated_log_kow', sa.Float(), nullable=True))
    op.add_column('chemical', sa.Column('estimated_solubility', sa.Float(), nullable=True))
    op.add_column('chemical', sa.Column('experimental_henry_constant', sa.Float(), nullable=True))
    op.add_column('chemical', sa.Column('experimental_log_kow', sa.Float(), nullable=True))
    op.add_column('chemical', sa.Column('experimental_solubility', sa.Float(), nullable=True))
    op.add_column('chemical', sa.Column('user_corrected_experimental_henry_constant', sa.Float(), nullable=True))
    op.add_column('chemical', sa.Column('user_corrected_experimental_log_kow', sa.Float(), nullable=True))
    op.add_column('chemical', sa.Column('user_corrected_experimental_solubility', sa.Float(), nullable=True))
    op.drop_column('chemical', 'properties')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chemical', sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('chemical', 'user_corrected_experimental_solubility')
    op.drop_column('chemical', 'user_corrected_experimental_log_kow')
    op.drop_column('chemical', 'user_corrected_experimental_henry_constant')
    op.drop_column('chemical', 'experimental_solubility')
    op.drop_column('chemical', 'experimental_log_kow')
    op.drop_column('chemical', 'experimental_henry_constant')
    op.drop_column('chemical', 'estimated_solubility')
    op.drop_column('chemical', 'estimated_log_kow')
    op.drop_column('chemical', 'estimated_henry_constant')
    # ### end Alembic commands ###
