"""added chemical molecular weight

Revision ID: f05bc5ceed3e
Revises: 4340795a89ef
Create Date: 2020-05-07 11:47:03.796980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f05bc5ceed3e'
down_revision = '4340795a89ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chemical', sa.Column('molecular_weight', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chemical', 'molecular_weight')
    # ### end Alembic commands ###
